spring:
  application:
    name: user-feign
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.112.1:8848   # 注意改成你的nacos地址
    sentinel:
      enabled: true
      transport:
        dashboard: 192.168.112.1:8888  # 注意改成你的地址和端口

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  sentinel:
    enabled: true
